Rewritten and commented src/logs.py
zayKenyon/VALORANT-rank-yoinker pull request #136
Opened 2023-02-12 20:54 UTC by nanometer5088

The logging logic was confusing and not commented, so I've parcially rewritten the code and throughly commented it.

2023-02-12 20:57 UTC, nanometer5088 commented
Just adding that it does not change any code functionality - the log will work the same way as it did before.

It's just cleaner and easier to contribute now :1st_place_medal:

2023-02-12 21:07 UTC, zayKenyon requested changes

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +# This code imports the `glob`, `os`, and `time` modules
Please do not use descriptive comments for lines like this, it's obvious what is done here.

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +# The `Logging` class is defined
^

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +    # The class constructor initializes the `logFileOpened` attribute as `False`
^
A better comment would be to explain what that attribute does, but that's tenuous.

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +    # The `log` method takes a string `log_string` as an argument
^
A better comment would be to explain what `log_string` is.

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +        # The logs directory is determined
^

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +        # If the logs directory does not exist, it is created
I'd argue this is unnecessary, `if not os.path.exists()` reads similarly to standard English.

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +        # A list of log files is obtained using the `glob` module
^

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +        # The log file numbers are extracted from the filenames
This is a good comment.

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +        # If no log files exist, a log-0.txt file is created
```suggestion
        # Creates a log file if none are present.
```

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +        # The log file name is determined
A better comment would break down the different parts of the statement.

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +        # The log file is opened and written to
Unnecessary.

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +            # The current time is formatted
^

2023-02-12 21:07 UTC, zayKenyon commented on src/logs.py
> +            # The log string is written to the file with the current time as a prefix
^

2023-02-12 21:12 UTC, zayKenyon commented
In general I'd say to make sure you're not stating the obvious. Common philosophy is that comments should be used when code is hard to read; when reading good code, you won't need comments. I appreciate your syntax and grammar within the comments though.

2023-02-12 21:36 UTC, nanometer5088 commented
I've changed what you suggested, take a look :man_technologist:

2023-02-12 21:38 UTC, zayKenyon requested changes

2023-02-12 21:38 UTC, zayKenyon commented on src/logs.py
> +    # log_string is a string that represents the log message that will be written to the log file.
```suggestion
    # `log_string` is a string that is the log message that will be written to the log file. 
```

2023-02-12 21:39 UTC, nanometer5088 commented on src/logs.py
> +    # log_string is a string that represents the log message that will be written to the log file.
Ah, fair enough.

2023-02-12 21:40 UTC, zayKenyon commented on src/logs.py
> +        # A list of log files is obtained using the `glob` module
Please address this.

2023-02-12 21:47 UTC, nanometer5088 commented on src/logs.py
> +        # A list of log files is obtained using the `glob` module
done

2023-02-12 21:55 UTC, zayKenyon approved these changes

2023-02-14 02:46 UTC, nanometer5088 commented
Oh damn wrong button sorry

2023-04-04 16:32 UTC, zayKenyon approved these changes

2023-05-18 22:27 UTC, merged